# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import * 
from PyQt5.QtGui import * 
import requests

ultime_azioni = [] 

data = {
    "action": "TurnOff",    # "TurnOff", "TurnOn", "print"
    "DockerID": "2",        # "1", "2", "3"
    "port": None,           # None, 8001, 8002, 8003 
    "RaspberryID": None     #"192.168.43.147", "192.168.43.188"
}

elenco_docker= ["1","2","3"]
docker_selected = ""
raspberry_selected = None
 
SERVER_IP = 'http://192.168.1.70:8000/'

RSP_1_active = [""]
RSP_2_active = [""]

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(60, 90, 161, 351))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 159, 349))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.radioButton = []
        i=0
        for item in elenco_docker :
            self.radioButton.append(QtWidgets.QRadioButton(self.scrollAreaWidgetContents))
            self.radioButton[i].setGeometry(QtCore.QRect(10, 40 + i*30, 112, 23))
            self.radioButton[i].setObjectName("radioButton")
            self.radioButton[i].clicked.connect(self.checkDocker)

            i=i+1
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 140, 20))
        self.label_3.setObjectName("label_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.turnonButton = QtWidgets.QPushButton(self.centralwidget)
        self.turnonButton.setGeometry(QtCore.QRect(160, 490, 210, 51))
        self.turnonButton.setObjectName("turnonButton")
        self.turnonButton.clicked.connect(self.turnon)


        self.turnofButton = QtWidgets.QPushButton(self.centralwidget)
        self.turnofButton.setGeometry(QtCore.QRect(440, 490, 201, 51))
        self.turnofButton.setObjectName("turnofButton")
        self.turnofButton.clicked.connect(self.turnoff)

        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(230, 90, 161, 351))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 159, 349))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.radioButton_5 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 40, 140, 23))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_5.clicked.connect(self.checkRaspberry)

        self.radioButton_6 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 70, 140, 23))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_6.clicked.connect(self.checkRaspberry)

        self.radioButton_7 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 100, 140, 23))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_7.clicked.connect(self.checkRaspberry)

        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.label_4.setObjectName("label_4")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setFont(QFont('Arial', 25))
        self.label_2.setGeometry(QtCore.QRect(60, 30, 671, 41))
        self.label_2.setObjectName("label_2")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(400, 90, 161, 351))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 159, 349))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.label_5.setObjectName("label_5")
        self.textBrowser = QLineEdit(self.scrollAreaWidgetContents_3)
        self.textBrowser.setGeometry(QtCore.QRect(10, 40, 101, 20))
        self.textBrowser.setObjectName("textBrowser")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_4.setGeometry(QtCore.QRect(570, 90, 161, 351))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 159, 349))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 140, 20))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label.setGeometry(QtCore.QRect(10, 39, 140, 21))
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 140, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 140, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 140, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_10.setGeometry(QtCore.QRect(10, 230, 140, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 140, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_12.setGeometry(QtCore.QRect(10, 189, 140, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_13.setGeometry(QtCore.QRect(10, 210, 140, 21))
        self.label_13.setObjectName("label_13")
        self.updateButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.updateButton.setGeometry(QtCore.QRect(30, 300, 100, 40))
        self.updateButton.setObjectName("updateButton")
        self.updateButton.clicked.connect(self.updatestatus)

        self.label_azioni = QtWidgets.QLabel(self.centralwidget)
        self.label_azioni.setFont(QFont('Arial', 10))
        self.label_azioni.setGeometry(QtCore.QRect(60, 540, 201, 51))
        self.label_azioni.setObjectName("label_2")
        
        self.label_azioni_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_azioni_1.setFont(QFont('Arial', 9))
        self.label_azioni_1.setGeometry(QtCore.QRect(60, 570, 601, 51))
        self.label_azioni_1.setObjectName("label_2")
        
        self.label_azioni_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_azioni_2.setFont(QFont('Arial', 9))
        self.label_azioni_2.setGeometry(QtCore.QRect(60, 600, 601, 51))
        self.label_azioni_2.setObjectName("label_2")
        
        self.label_azioni_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_azioni_3.setFont(QFont('Arial', 9))
        self.label_azioni_3.setGeometry(QtCore.QRect(60, 630, 601, 51))
        self.label_azioni_3.setObjectName("label_2")

        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        i=0
        for item in elenco_docker :
            self.radioButton[i].setText(_translate("MainWindow","docker"+ item))
            i=i+1
        self.label_3.setText(_translate("MainWindow", "LIST OF DOCKERS"))
        self.turnonButton.setText(_translate("MainWindow", "Turn ON"))
        self.turnofButton.setText(_translate("MainWindow", "Turn OFF"))
        self.radioButton_5.setText(_translate("MainWindow", "RASPBERRY 1"))
        self.radioButton_6.setText(_translate("MainWindow", "RASPBERRY 2"))
        self.radioButton_7.setText(_translate("MainWindow", "AUTOMATIC"))
        self.label_4.setText(_translate("MainWindow", "RASPBERRY"))
        self.label_2.setText(_translate("MainWindow", "WAKE ON LAN PROJECT "))
        self.label_5.setText(_translate("MainWindow", "PORT :"))
        self.label_6.setText(_translate("MainWindow", "STATUS "))
        self.label.setText(_translate("MainWindow", "RASPBERRY 1:"))
        self.label_7.setText(_translate("MainWindow", ""))
        self.label_8.setText(_translate("MainWindow", ""))
        self.label_9.setText(_translate("MainWindow", ""))
        self.label_10.setText(_translate("MainWindow", ""))
        self.label_11.setText(_translate("MainWindow", ""))
        self.label_12.setText(_translate("MainWindow", "RASPBERRY 2:"))
        self.label_13.setText(_translate("MainWindow", ""))
        self.label_azioni.setText(_translate("MainWindow", "Ultime azioni:"))

        self.label_azioni_1.setText(_translate("MainWindow", ""))
        self.label_azioni_2.setText(_translate("MainWindow", ""))
        self.label_azioni_3.setText(_translate("MainWindow", ""))

        self.updateButton.setText(_translate("MainWindow", "UPDATE"))

        # method called by radio button
    def checkDocker(self):

        global docker_selected

        for radio_button in self.radioButton : 
            # checking if it is checked
            if radio_button.isChecked():
                
                # changing docker_selected
                docker_selected = radio_button.text()

    def checkRaspberry(self):

        global raspberry_selected

        if(self.radioButton_5.isChecked()):
            raspberry_selected = self.radioButton_5.text()
        if(self.radioButton_6.isChecked()):
            raspberry_selected = self.radioButton_6.text()
        if(self.radioButton_7.isChecked()):
            raspberry_selected = None

    def update_azioni(self):
        
        global ultime_azioni    

        _translate = QtCore.QCoreApplication.translate
        if(len(ultime_azioni)-1 >= 0):
            self.label_azioni_1.setText(_translate("MainWindow", ultime_azioni[len(ultime_azioni)-1]))
        if(len(ultime_azioni)-2 >= 0):
            self.label_azioni_2.setText(_translate("MainWindow", ultime_azioni[len(ultime_azioni)-2]))
        if(len(ultime_azioni)-3 >= 0):
            self.label_azioni_3.setText(_translate("MainWindow", ultime_azioni[len(ultime_azioni)-3]))
         
         

        # method called by Turn On button
    def turnon(self):

        global docker_selected

        print("Richiesta TURN ON docker : " + docker_selected)

        if(docker_selected != ""):

            data["action"] = "TurnOn"
            data["DockerID"] = docker_selected.replace("docker","")
            data["RaspberryID"] = raspberry_selected
            if(self.textBrowser.text() != ""):
                data["port"] = self.textBrowser.text()
            else :
                data["port"] = None
            
            print(data)
            r = requests.post(SERVER_IP,json=data)
            if(len(ultime_azioni) >2):
                ultime_azioni.pop(0)
            ultime_azioni.append(str(r.text))

            self.update_azioni()
            


    # method called by Turn Off button
    def turnoff(self):

        global docker_selected

        if(docker_selected != ""):

            print("Richiesta TURN OFF docker : " + docker_selected)
            data["action"] = "TurnOff"
            data["DockerID"] = docker_selected.replace("docker","")
            data["RaspberryID"] = raspberry_selected

            if(self.textBrowser.text() != ""):
                data["port"] = self.textBrowser.text()
            else :
                data["port"] = None
                
            print(data)
            r = requests.post(SERVER_IP,json=data)
            if(len(ultime_azioni) >2):
                ultime_azioni.pop(0)
            ultime_azioni.append(str(r.text))

            self.update_azioni()

    def updatestatus(self):

        _translate = QtCore.QCoreApplication.translate


        data["action"] = "print"
        #message = "IMAGE               PORTS                NAMES\nnginx               0.0.0.0:80->80/tcp   nginx\nPINO               0.0.0.0:80->80/tcp   PINO\n\nIMAGE               PORTS                NAMES\nnginx               0.0.0.0:80->80/tcp   nginx\nENRI               0.0.0.0:80->80/tcp   PERRY"
        
        r = requests.post(SERVER_IP,json=data)
        message = r.text
        docker_ps = message.split("\n\n")    
        docker_righe = docker_ps[0].split("\n")
        lista_docker = []
        for riga in docker_righe:
            lista_docker.append(riga.split("               "))
        if(len(lista_docker) == 1): 
            self.label_7.setText(_translate("MainWindow", lista_docker[0][0]))
            self.label_8.setText(_translate("MainWindow", ""))
            self.label_9.setText(_translate("MainWindow", ""))

        if(len(lista_docker) == 2): 
            self.label_7.setText(_translate("MainWindow", lista_docker[0][0]))
            self.label_8.setText(_translate("MainWindow", lista_docker[1][0]))
            self.label_9.setText(_translate("MainWindow", ""))
        if(len(lista_docker) == 3): 
            self.label_7.setText(_translate("MainWindow", lista_docker[0][0]))
            self.label_8.setText(_translate("MainWindow", lista_docker[1][0]))
            self.label_9.setText(_translate("MainWindow", lista_docker[2][0]))
        

        docker_righe = docker_ps[1].split("\n")
        lista_docker = []
        for riga in docker_righe:
            lista_docker.append(riga.split("               "))
        if(len(lista_docker) == 1): 
            self.label_13.setText(_translate("MainWindow", lista_docker[0][0]))
            self.label_10.setText(_translate("MainWindow", ""))
            self.label_11.setText(_translate("MainWindow", ""))

        if(len(lista_docker) == 2): 
            self.label_13.setText(_translate("MainWindow", lista_docker[0][0]))
            self.label_10.setText(_translate("MainWindow", lista_docker[1][0]))
            self.label_11.setText(_translate("MainWindow", ""))
        if(len(lista_docker) == 3): 
            self.label_13.setText(_translate("MainWindow", lista_docker[0][0]))
            self.label_10.setText(_translate("MainWindow", lista_docker[1][0]))
            self.label_11.setText(_translate("MainWindow", lista_docker[2][0]))

        print(lista_docker)
        
